### ISSUE TITLE
facts_hash_hiera_merge removed in 4.0.0?

### ISSUE THREAD

**Issue by Sparc0** [ghoneycutt/puppet-module-facter#72]
Below hiera config in 4.0.0 does not exist and had to revert to 3.5.0 to not overwrite my facter file.  
facter::facts_hash_hiera_merge: true

Any reason why?

**Comment by wolfaba** [comment]
You can use following to merge `facter::facts_hash`. Maybe that's the reason, why it's not required anymore
```
lookup_options:
  facter::facts_hash:
    merge:
      strategy: deep
      merge_hash_arrays: true
```

**Comment by Sparc0** [comment]
That lookup_options config did not work with 4.0.0 it still overwrites manual changes i done in my facter file. 
I tried multiple lookup_options even with regex to match anything after facter:: but no luck.

**Comment by wolfaba** [comment]
We set following in `data/common.yaml` (as described in https://www.puppet.com/docs/puppet/8/hiera_merging.html#overriding-merge-behavior) and it works

```
lookup_options:
  facter::facts_hash:
    merge:
      strategy: deep
      merge_hash_arrays: true
```
Could you maybe paste general parts of your yaml configuration? Maybe the lookup_options for the facter are not loaded in hiera? And could you paste the `puppet agent -t --noop` output, what change does puppet want to make.

> I tried multiple lookup_options even with regex to match anything after facter::

You don't need to match any thing. The class is `facter` and it has parameter `facts_hash` therefore `facter::facts_hash` is correct.

**Comment by Sparc0** [comment]
my `hiera.yaml`
```
---
version: 5
defaults:
  datadir: "/etc/puppetlabs/code/environments/%{environment}/hieradata"
  data_hash: yaml_data

hierarchy:
  - name: "Secret data: common"
    lookup_key: eyaml_lookup_key
    path: "common.eyaml"
    options:
      pkcs7_private_key: /etc/puppetlabs/puppet/eyaml/private_key.pkcs7.pem
      pkcs7_public_key: /etc/puppetlabs/puppet/eyaml/public_key.pkcs7.pem

  - name: "Node"
    path: "node/%{::fqdn}.yaml"

  - name: "Profile"
    path: "profile/%{::profile}.yaml"

  - name: "Role"
    path: "role/%{::role}.yaml"

  - name: "Groups"
    path: "groups/%{::groups}.yaml"

  - name: "Domain"
    path: "domain/%{::domain}.yaml"

  - name: "OS"
    paths:
      - "os/%{os.family}.yaml"
      - "os/%{os.name}.yaml"

  - name: "Common"
    path: "common.yaml"

```

my `hieradata/common.yaml` i have this 
```
---
classes:
  - facter

# facter
facter::facts_file: 'facts.txt'

lookup_options:
  facter::facts_hash:
    merge:
      strategy: deep
      merge_hash_arrays: true
```

This is my `puppet agent -t --noop` output
```
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Notice: Requesting catalog from redacted:8140 (192.168.1.15)
Notice: Catalog compiled by redactedmaster
Info: Applying configuration version '1738168939'
Notice: /Stage[main]/Adcli::Join/Exec[adcli_join]/returns: current_value 'notrun', should be ['0'] (noop) (corrective)
Notice: Class[Adcli::Join]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Types/Types::Type[service]/Service[tftp]/ensure: current_value 'stopped', should be 'running' (noop)
Info: /Stage[main]/Types/Types::Type[service]/Service[tftp]: Unscheduling refresh on Service[tftp]
Notice: Types::Type[service]: Would have triggered 'refresh' from 1 event
Notice: Class[Types]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Facter/Concat[facts_file]/File[/etc/facter/facts.d/facts.txt]/content:
--- /etc/facter/facts.d/facts.txt    2025-01-29 16:50:12.219477771 +0100
+++ /tmp/puppet-file20250129-107397-1uamu7k     2025-01-29 17:42:23.849473135 +0100
@@ -2,4 +2,3 @@
 #DO NOT EDIT
 site_code=ams
-profile=http

Notice: /Stage[main]/Facter/Concat[facts_file]/File[/etc/facter/facts.d/facts.txt]/content: current_value '{sha256}bdc3674efdb22a7794e5eb072dddbc3c8ad8cb8ff3896e9be851ef46cfa29c7b', should be '{sha256}9cedb8a305f91140332434c792b17b60c0945e97c124a32fb085ab99d3b457d8' (noop)
Notice: facts_file: Would have triggered 'refresh' from 1 event
Notice: Concat[facts_file]: Would have triggered 'refresh' from 2 events
Notice: /Stage[main]/Sssd::Service/Service[sssd.service]/ensure: current_value 'stopped', should be 'running' (noop)
Info: /Stage[main]/Sssd::Service/Service[sssd.service]: Unscheduling refresh on Service[sssd.service]
Notice: Class[Sssd::Service]: Would have triggered 'refresh' from 1 event
Notice: Class[Sssd]: Would have triggered 'refresh' from 1 event
Notice: Class[Facter]: Would have triggered 'refresh' from 1 event
Notice: Stage[main]: Would have triggered 'refresh' from 5 events
Notice: Applied catalog in 1.63 seconds
```

The value `site_code=ams` comes from a file under `domain/%{::domain}.yaml`
